volumes:
  db:
services:
  http:
    container_name: space-imobi-http
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - ${DOCKER_HTTP_PORT}:80
    mem_limit: 100M
    volumes:
      - ./:/var/www
      - .docker/nginx/default.d/:/etc/nginx/conf.d/
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - life
  app:
    container_name: php-life
    build: 
      args:
        user: ${DOCKER_USER_ID}
        uid: ${DOCKER_GROUP_ID}
        context: . 
        dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - life
  db:
    container_name: space-imobi-db
    image: mysql:8
    restart: unless-stopped
    mem_limit: 600M
    environment:
      MYSQL_DATABASE: ${DOCKER_DB_DATABASE}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
        - db:/var/lib/mysql
    ports:
      - ${DOCKER_DB_PORT}:3306
    networks:
      - life

networks:
  life:
    driver: bridge

